### ISSUE TITLE
duplicated entrys for spring-cloud-kubernetes in https://spring.io/projects/spring-cloud

### ISSUE THREAD

**Issue by ZhangChaoWN** [spring-projects/gh-pages#26]
I see duplicated entrys for spring-cloud-kubernetes https://spring.io/projects/spring-cloud

![image](https://user-images.githubusercontent.com/9245192/55126092-fdda1800-5146-11e9-9ac9-b0b9d22bdcc8.png)

**Comment by bclozel** [comment]
Thanks for the heads up, this is now fixed.
For the record this is not something that is dealt with here, but rather something we manage in the admin page of https://github.com/spring-io/sagan/.

Cheers!
