### ISSUE TITLE
Make API doc links optional

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/gh-pages#6]
This is somewhat similar to spring-io/sagan#388.

The Spring IO Platform doesn't have any API docs which causes a minor glitch on its project page as the reference docs link is rendered with a separator even though there's no API docs link for it to be separated from. I've worked around the problem [with my own changes](https://github.com/spring-io/platform/commit/cf77f1b7f4be0ab6ba89c6bd4da7bab58c0b24b6) but I wonder if a more general-purpose solution might be possible.

**Comment by dsyer** [comment]
That change looks worthy of a pull request to me.

**Comment by wilkinsona** [comment]
The CSS change in my hack isn't generally applicable. For projects that have both API docs and reference docs my change will get rid of the separator that goes between them.

**Comment by gregturn** [comment]
Looking into things, it appears the simplest fix is to put conditional checks at https://github.com/spring-projects/gh-pages/blob/gh-pages/_includes/widget_templates.html#L20-L23. I can work on this since I've recently done some hacking on underscore.js templates.

**Comment by bclozel** [comment]
Fixed by #12
